-- DESERT SPRINGS DEMO, part 3: 30 service listings, 6 events, and the final counts
-- Paste into the SQL Editor of the desert-springs-demo project ONLY. Never the live project.
-- Every name, business and address here is invented; all emails are @example.com.
-- Run after part 2. The last query shows the counts: that table is your result.

do $$
begin
  if exists (select 1 from auth.users where lower(coalesce(email, '')) not like '%@example.com') then
    raise exception 'STOPPED: this database has accounts that are not @example.com, so it looks like real data. Nothing was changed.';
  end if;
  if (select count(*) from auth.users) < 120 then
    raise exception 'STOPPED: run parts 1 and 2 first. Nothing was changed.';
  end if;
  if exists (select 1 from public.pro_listings) or exists (select 1 from public.events) then
    raise exception 'STOPPED: listings or events already exist. Run 0-reset-optional.sql to start over. Nothing was changed.';
  end if;
end $$;

-- Business accounts (the app keeps these out of the member directory).
insert into auth.users
  (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
   raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
   confirmation_token, recovery_token, email_change_token_new, email_change)
select
  '00000000-0000-0000-0000-000000000000', v.id::uuid, 'authenticated', 'authenticated', v.email, '',
  now() - interval '30 days', '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('name', v.name, 'account_type', 'business'),
  now() - interval '30 days', now() - interval '30 days', '', '', '', ''
from (values
  ('e732d75f-e282-5e70-ad31-3f9926d9935a', 'pro-sagebrush-canine-academy@example.com', 'Ulises Underhill'),
  ('92b81db4-87bd-56fd-ad5c-62ce63b4f5f2', 'pro-good-habits-dog-training@example.com', 'Ivan Whitlock'),
  ('c7823899-9497-538c-af97-31d055a699f1', 'pro-arroyo-recall-co@example.com', 'Ivan Ellery'),
  ('4d302987-acea-5617-a265-80bce55c44e2', 'pro-calm-paws-behavior-studio@example.com', 'Vance Dunmore'),
  ('13d542e1-0bf0-5111-a7b6-820e93b36e3e', 'pro-trailhead-training@example.com', 'Mateo Yarrow'),
  ('fc38d830-88bd-5ff0-a54d-e6abde6051de', 'pro-pawsitive-start@example.com', 'Ivan Sandoval-Reyes'),
  ('ebb3048a-4cbb-5bcd-ac6d-a5793f7fca10', 'pro-sunny-paws-mobile-grooming@example.com', 'Zane Kirkland'),
  ('efcd1846-3801-599a-abac-82944c33f82b', 'pro-prickly-pear-grooming-van@example.com', 'Dario Calloway'),
  ('bfd633b0-2daf-575b-af4f-e6b038a7be15', 'pro-tumbleweed-tidy-up@example.com', 'Pierce Dunmore'),
  ('fa500300-a524-55ef-a5d9-5bdeee9b2d2c', 'pro-desert-rose-dog-spa@example.com', 'Quentin Jessup'),
  ('084b5236-90c0-5590-a2b5-dfb7a8d96e02', 'pro-the-sandstone-scrub@example.com', 'Ivan Zimmerman'),
  ('65cce4ae-1ecb-5612-abb3-a8962d54cd85', 'pro-cactus-cuts-mobile-salon@example.com', 'Yosef Kirkland'),
  ('eaab0f3d-2b74-54f7-ae56-3a9d77d52e87', 'pro-roadrunner-dog-walking@example.com', 'Marisol Holloway'),
  ('b2ef97f4-aeca-56cb-a758-f1ae9ef44b18', 'pro-early-bird-walkers@example.com', 'Ulises Holloway'),
  ('3402e0cd-ac7e-58e0-a4f2-389aee15be23', 'pro-mesa-miles@example.com', 'Zane Holloway'),
  ('caf34ca2-cdfe-54b2-ab70-d8bd662a21d8', 'pro-slow-stroll-seniors@example.com', 'Yosef Alder'),
  ('f753f273-e4ff-50b8-aa8c-71fe09e27125', 'pro-willow-canyon-walkers@example.com', 'Pierce Quill'),
  ('79aaaf5f-321a-549f-aa34-c94ae884ef48', 'pro-happy-trails-pet-care@example.com', 'Jasper Brennan'),
  ('0293f951-e0a1-541d-aa22-f47fc1f40e01', 'pro-home-sweet-home-pet-sitting@example.com', 'Pierce Lockridge'),
  ('ba93102b-2686-5051-af99-6fc304e2148e', 'pro-oasis-overnights@example.com', 'Dario Oakes'),
  ('3d0e9173-b421-579e-a29b-2bc1e07ba7f8', 'pro-agave-hills-pet-sitters@example.com', 'Elias Holloway'),
  ('af4d940a-a7ff-5546-a6f0-32ed53a7d78c', 'pro-sundown-sitters@example.com', 'Yosef Maddox'),
  ('5b58f780-d3de-5ba1-aa6d-bcd905a8f6c7', 'pro-cozy-pup-retreat@example.com', 'Ivan Iverson'),
  ('27701535-a0a9-5161-a6b2-277a056fcd42', 'pro-stay-play-sitters@example.com', 'Elias Sandoval-Reyes'),
  ('203aebba-f305-5303-a78c-c5c9af8c0c29', 'pro-sunrise-house-call-vet@example.com', 'Gavin Pemberton'),
  ('d3fab2cb-92f9-5bbc-ad2f-549b24f3128e', 'pro-gentle-paws-mobile-veterinary@example.com', 'Mateo Pemberton'),
  ('0549f202-359f-5af6-a5e8-f9178284e39a', 'pro-saguaro-senior-pet-care@example.com', 'Marisol Quill'),
  ('1567f807-30d5-531b-a20d-6c45c1f58a44', 'pro-mesa-mobile-veterinary@example.com', 'Kellan Iverson'),
  ('88d2f086-10f1-5ee4-afcd-5b8f2e803c5b', 'pro-cactus-flats-house-calls@example.com', 'Xavier Alder'),
  ('127451cd-67e4-5b84-a990-038ec19ccba7', 'pro-arroyo-home-vet@example.com', 'Dario Brennan')
) as v(id, email, name);

insert into public.pro_listings
  (user_id, business_name, contact_name, headline, about, services, cities, phone, email, website,
   rate_note, years_experience, credentials, insured, status)
select v.user_id::uuid, v.business_name, v.contact_name, v.headline, v.about,
       string_to_array(v.services, '|'), string_to_array(v.cities, '|'),
       v.phone, v.email, v.website, v.rate_note, v.years, v.credentials, v.insured, 'published'
from (values
  ('e732d75f-e282-5e70-ad31-3f9926d9935a', 'Sagebrush Canine Academy', 'Ulises Underhill', 'Obedience and puppy basics for real life.', 'Sagebrush Canine Academy is a made-up business in the Desert Springs demo. Obedience and puppy basics for real life. Ulises has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'training', 'Mesa Verde|Desert Springs', '(555) 555-0101', 'pro-sagebrush-canine-academy@example.com', 'https://example.com/sagebrush-canine-academy', 'Private lessons from $80', 9, 'Sample certification (demo)', true),
  ('92b81db4-87bd-56fd-ad5c-62ce63b4f5f2', 'Good Habits Dog Training', 'Ivan Whitlock', 'Gentle, reward-based coaching for every household.', 'Good Habits Dog Training is a made-up business in the Desert Springs demo. Gentle, reward-based coaching for every household. Ivan has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'training', 'Oasis Park|Mesa Verde|Cactus Flats|Sandstone Heights|Desert Springs', '(555) 555-0102', 'pro-good-habits-dog-training@example.com', 'https://example.com/good-habits-dog-training', 'Private lessons from $80', 3, 'Sample certification (demo)', false),
  ('c7823899-9497-538c-af97-31d055a699f1', 'Arroyo Recall Co.', 'Ivan Ellery', 'Reliable off-leash skills, built step by step.', 'Arroyo Recall Co. is a made-up business in the Desert Springs demo. Reliable off-leash skills, built step by step. Ivan has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'training', 'Mesa Verde|Agave Hills|Oasis Park|Desert Springs', '(555) 555-0103', 'pro-arroyo-recall-co@example.com', 'https://example.com/arroyo-recall-co', 'Private lessons from $80', 18, 'Sample certification (demo)', false),
  ('4d302987-acea-5617-a265-80bce55c44e2', 'Calm Paws Behavior Studio', 'Vance Dunmore', 'Help for reactive and anxious dogs.', 'Calm Paws Behavior Studio is a made-up business in the Desert Springs demo. Help for reactive and anxious dogs. Vance has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'training', 'Cactus Flats|Sandstone Heights', '(555) 555-0104', 'pro-calm-paws-behavior-studio@example.com', 'https://example.com/calm-paws-behavior-studio', 'Private lessons from $80', 3, 'Sample certification (demo)', true),
  ('13d542e1-0bf0-5111-a7b6-820e93b36e3e', 'Trailhead Training', 'Mateo Yarrow', 'Hiking manners and trail confidence.', 'Trailhead Training is a made-up business in the Desert Springs demo. Hiking manners and trail confidence. Mateo has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'training', 'Cactus Flats|Oasis Park|Mesa Verde|Agave Hills|Willow Canyon', '(555) 555-0105', 'pro-trailhead-training@example.com', 'https://example.com/trailhead-training', 'Private lessons from $80', 8, 'Sample certification (demo)', true),
  ('fc38d830-88bd-5ff0-a54d-e6abde6051de', 'Pawsitive Start', 'Ivan Sandoval-Reyes', 'Puppy classes that set you up for success.', 'Pawsitive Start is a made-up business in the Desert Springs demo. Puppy classes that set you up for success. Ivan has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'training', 'Sandstone Heights|Cactus Flats|Oasis Park', '(555) 555-0106', 'pro-pawsitive-start@example.com', 'https://example.com/pawsitive-start', 'Private lessons from $80', 10, 'Sample certification (demo)', true),
  ('ebb3048a-4cbb-5bcd-ac6d-a5793f7fca10', 'Sunny Paws Mobile Grooming', 'Zane Kirkland', 'A full groom at your front door.', 'Sunny Paws Mobile Grooming is a made-up business in the Desert Springs demo. A full groom at your front door. Zane has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'grooming', 'Cactus Flats|Willow Canyon|Sandstone Heights|Mesa Verde', '(555) 555-0107', 'pro-sunny-paws-mobile-grooming@example.com', 'https://example.com/sunny-paws-mobile-grooming', 'Full groom from $70', 11, null, true),
  ('efcd1846-3801-599a-abac-82944c33f82b', 'Prickly Pear Grooming Van', 'Dario Calloway', 'Baths, trims and nail care, no kennel time.', 'Prickly Pear Grooming Van is a made-up business in the Desert Springs demo. Baths, trims and nail care, no kennel time. Dario has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'grooming', 'Desert Springs|Cactus Flats|Palo Alto Wells', '(555) 555-0108', 'pro-prickly-pear-grooming-van@example.com', 'https://example.com/prickly-pear-grooming-van', 'Full groom from $70', 9, null, true),
  ('bfd633b0-2daf-575b-af4f-e6b038a7be15', 'Tumbleweed Tidy-Up', 'Pierce Dunmore', 'Low-stress grooming for nervous dogs.', 'Tumbleweed Tidy-Up is a made-up business in the Desert Springs demo. Low-stress grooming for nervous dogs. Pierce has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'grooming', 'Cactus Flats|Willow Canyon', '(555) 555-0109', 'pro-tumbleweed-tidy-up@example.com', 'https://example.com/tumbleweed-tidy-up', 'Full groom from $70', 10, null, true),
  ('fa500300-a524-55ef-a5d9-5bdeee9b2d2c', 'Desert Rose Dog Spa', 'Quentin Jessup', 'Spa days for fluffy dogs.', 'Desert Rose Dog Spa is a made-up business in the Desert Springs demo. Spa days for fluffy dogs. Quentin has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'grooming', 'Oasis Park|Mesa Verde', '(555) 555-0110', 'pro-desert-rose-dog-spa@example.com', 'https://example.com/desert-rose-dog-spa', 'Full groom from $70', 12, null, true),
  ('084b5236-90c0-5590-a2b5-dfb7a8d96e02', 'The Sandstone Scrub', 'Ivan Zimmerman', 'Quick baths and de-shedding treatments.', 'The Sandstone Scrub is a made-up business in the Desert Springs demo. Quick baths and de-shedding treatments. Ivan has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'grooming', 'Agave Hills|Cactus Flats|Willow Canyon', '(555) 555-0111', 'pro-the-sandstone-scrub@example.com', 'https://example.com/the-sandstone-scrub', 'Full groom from $70', 12, null, true),
  ('65cce4ae-1ecb-5612-abb3-a8962d54cd85', 'Cactus Cuts Mobile Salon', 'Yosef Kirkland', 'Breed-specific cuts with a gentle touch.', 'Cactus Cuts Mobile Salon is a made-up business in the Desert Springs demo. Breed-specific cuts with a gentle touch. Yosef has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'grooming', 'Oasis Park|Willow Canyon|Palo Alto Wells', '(555) 555-0112', 'pro-cactus-cuts-mobile-salon@example.com', 'https://example.com/cactus-cuts-mobile-salon', 'Full groom from $70', 5, null, true),
  ('eaab0f3d-2b74-54f7-ae56-3a9d77d52e87', 'Roadrunner Dog Walking', 'Marisol Holloway', 'Midday walks and small pack adventures.', 'Roadrunner Dog Walking is a made-up business in the Desert Springs demo. Midday walks and small pack adventures. Marisol has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'walking', 'Sandstone Heights|Agave Hills|Mesa Verde', '(555) 555-0113', 'pro-roadrunner-dog-walking@example.com', 'https://example.com/roadrunner-dog-walking', 'From $25 per 30 minute walk', 6, null, true),
  ('b2ef97f4-aeca-56cb-a758-f1ae9ef44b18', 'Early Bird Walkers', 'Ulises Holloway', 'Cool morning walks before the heat.', 'Early Bird Walkers is a made-up business in the Desert Springs demo. Cool morning walks before the heat. Ulises has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'walking', 'Mesa Verde|Oasis Park|Palo Alto Wells|Desert Springs|Willow Canyon', '(555) 555-0114', 'pro-early-bird-walkers@example.com', 'https://example.com/early-bird-walkers', 'From $25 per 30 minute walk', 8, null, true),
  ('3402e0cd-ac7e-58e0-a4f2-389aee15be23', 'Mesa Miles', 'Zane Holloway', 'Active walks for high-energy dogs.', 'Mesa Miles is a made-up business in the Desert Springs demo. Active walks for high-energy dogs. Zane has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'walking', 'Mesa Verde|Cactus Flats|Sandstone Heights|Palo Alto Wells', '(555) 555-0115', 'pro-mesa-miles@example.com', 'https://example.com/mesa-miles', 'From $25 per 30 minute walk', 7, null, false),
  ('caf34ca2-cdfe-54b2-ab70-d8bd662a21d8', 'Slow Stroll Seniors', 'Yosef Alder', 'Gentle walks for older dogs.', 'Slow Stroll Seniors is a made-up business in the Desert Springs demo. Gentle walks for older dogs. Yosef has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'walking', 'Mesa Verde|Sandstone Heights|Desert Springs|Willow Canyon|Palo Alto Wells', '(555) 555-0116', 'pro-slow-stroll-seniors@example.com', 'https://example.com/slow-stroll-seniors', 'From $25 per 30 minute walk', 2, null, true),
  ('f753f273-e4ff-50b8-aa8c-71fe09e27125', 'Willow Canyon Walkers', 'Pierce Quill', 'Reliable daily walks, GPS tracked.', 'Willow Canyon Walkers is a made-up business in the Desert Springs demo. Reliable daily walks, GPS tracked. Pierce has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'walking', 'Desert Springs|Cactus Flats|Mesa Verde', '(555) 555-0117', 'pro-willow-canyon-walkers@example.com', 'https://example.com/willow-canyon-walkers', 'From $25 per 30 minute walk', 11, null, true),
  ('79aaaf5f-321a-549f-aa34-c94ae884ef48', 'Happy Trails Pet Care', 'Jasper Brennan', 'Group hikes on weekends.', 'Happy Trails Pet Care is a made-up business in the Desert Springs demo. Group hikes on weekends. Jasper has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'walking', 'Desert Springs|Sandstone Heights|Cactus Flats|Mesa Verde|Palo Alto Wells', '(555) 555-0118', 'pro-happy-trails-pet-care@example.com', 'https://example.com/happy-trails-pet-care', 'From $25 per 30 minute walk', 6, null, true),
  ('0293f951-e0a1-541d-aa22-f47fc1f40e01', 'Home Sweet Home Pet Sitting', 'Pierce Lockridge', 'Overnights at your place so routines stay put.', 'Home Sweet Home Pet Sitting is a made-up business in the Desert Springs demo. Overnights at your place so routines stay put. Pierce has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'sitting', 'Oasis Park|Agave Hills|Sandstone Heights|Mesa Verde', '(555) 555-0119', 'pro-home-sweet-home-pet-sitting@example.com', 'https://example.com/home-sweet-home-pet-sitting', 'From $55 per night', 18, null, true),
  ('ba93102b-2686-5051-af99-6fc304e2148e', 'Oasis Overnights', 'Dario Oakes', 'Cozy boarding in a quiet home with a fenced yard.', 'Oasis Overnights is a made-up business in the Desert Springs demo. Cozy boarding in a quiet home with a fenced yard. Dario has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'sitting', 'Cactus Flats|Palo Alto Wells', '(555) 555-0120', 'pro-oasis-overnights@example.com', 'https://example.com/oasis-overnights', 'From $55 per night', 9, null, false),
  ('3d0e9173-b421-579e-a29b-2bc1e07ba7f8', 'Agave Hills Pet Sitters', 'Elias Holloway', 'Drop-in visits and holiday coverage.', 'Agave Hills Pet Sitters is a made-up business in the Desert Springs demo. Drop-in visits and holiday coverage. Elias has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'sitting', 'Desert Springs|Sandstone Heights', '(555) 555-0121', 'pro-agave-hills-pet-sitters@example.com', 'https://example.com/agave-hills-pet-sitters', 'From $55 per night', 7, null, true),
  ('af4d940a-a7ff-5546-a6f0-32ed53a7d78c', 'Sundown Sitters', 'Yosef Maddox', 'Sitting for dogs with special needs.', 'Sundown Sitters is a made-up business in the Desert Springs demo. Sitting for dogs with special needs. Yosef has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'sitting', 'Sandstone Heights|Cactus Flats|Oasis Park|Desert Springs', '(555) 555-0122', 'pro-sundown-sitters@example.com', 'https://example.com/sundown-sitters', 'From $55 per night', 15, null, true),
  ('5b58f780-d3de-5ba1-aa6d-bcd905a8f6c7', 'Cozy Pup Retreat', 'Ivan Iverson', 'Small-group boarding with plenty of cuddles.', 'Cozy Pup Retreat is a made-up business in the Desert Springs demo. Small-group boarding with plenty of cuddles. Ivan has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'sitting', 'Desert Springs|Willow Canyon', '(555) 555-0123', 'pro-cozy-pup-retreat@example.com', 'https://example.com/cozy-pup-retreat', 'From $55 per night', 7, null, false),
  ('27701535-a0a9-5161-a6b2-277a056fcd42', 'Stay & Play Sitters', 'Elias Sandoval-Reyes', 'Daytime sitting with lots of play.', 'Stay & Play Sitters is a made-up business in the Desert Springs demo. Daytime sitting with lots of play. Elias has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'sitting', 'Sandstone Heights|Willow Canyon|Palo Alto Wells', '(555) 555-0124', 'pro-stay-play-sitters@example.com', 'https://example.com/stay-play-sitters', 'From $55 per night', 17, null, true),
  ('203aebba-f305-5303-a78c-c5c9af8c0c29', 'Sunrise House Call Vet', 'Gavin Pemberton', 'Wellness visits at home.', 'Sunrise House Call Vet is a made-up business in the Desert Springs demo. Wellness visits at home. Gavin has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'vets', 'Mesa Verde|Desert Springs|Willow Canyon|Sandstone Heights|Oasis Park', '(555) 555-0125', 'pro-sunrise-house-call-vet@example.com', 'https://example.com/sunrise-house-call-vet', 'Home visit from $95', 12, null, true),
  ('d3fab2cb-92f9-5bbc-ad2f-549b24f3128e', 'Gentle Paws Mobile Veterinary', 'Mateo Pemberton', 'Stress-free exams and vaccines at your door.', 'Gentle Paws Mobile Veterinary is a made-up business in the Desert Springs demo. Stress-free exams and vaccines at your door. Mateo has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'vets', 'Sandstone Heights|Desert Springs', '(555) 555-0126', 'pro-gentle-paws-mobile-veterinary@example.com', 'https://example.com/gentle-paws-mobile-veterinary', 'Home visit from $95', 17, null, false),
  ('0549f202-359f-5af6-a5e8-f9178284e39a', 'Saguaro Senior Pet Care', 'Marisol Quill', 'In-home care and comfort for senior pets.', 'Saguaro Senior Pet Care is a made-up business in the Desert Springs demo. In-home care and comfort for senior pets. Marisol has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'vets', 'Cactus Flats|Sandstone Heights|Agave Hills|Palo Alto Wells|Oasis Park', '(555) 555-0127', 'pro-saguaro-senior-pet-care@example.com', 'https://example.com/saguaro-senior-pet-care', 'Home visit from $95', 16, null, false),
  ('1567f807-30d5-531b-a20d-6c45c1f58a44', 'Mesa Mobile Veterinary', 'Kellan Iverson', 'Mobile check-ups and lab work.', 'Mesa Mobile Veterinary is a made-up business in the Desert Springs demo. Mobile check-ups and lab work. Kellan has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'vets', 'Sandstone Heights|Willow Canyon|Mesa Verde|Cactus Flats', '(555) 555-0128', 'pro-mesa-mobile-veterinary@example.com', 'https://example.com/mesa-mobile-veterinary', 'Home visit from $95', 15, null, true),
  ('88d2f086-10f1-5ee4-afcd-5b8f2e803c5b', 'Cactus Flats House Calls', 'Xavier Alder', 'Compassionate in-home veterinary care.', 'Cactus Flats House Calls is a made-up business in the Desert Springs demo. Compassionate in-home veterinary care. Xavier has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'vets', 'Palo Alto Wells|Desert Springs', '(555) 555-0129', 'pro-cactus-flats-house-calls@example.com', 'https://example.com/cactus-flats-house-calls', 'Home visit from $95', 17, null, true),
  ('127451cd-67e4-5b84-a990-038ec19ccba7', 'Arroyo Home Vet', 'Dario Brennan', 'Preventive care and nutrition advice.', 'Arroyo Home Vet is a made-up business in the Desert Springs demo. Preventive care and nutrition advice. Dario has worked with dogs of every size and temperament and keeps every client''s routine front and center. This listing is sample content.', 'vets', 'Sandstone Heights|Agave Hills|Cactus Flats', '(555) 555-0130', 'pro-arroyo-home-vet@example.com', 'https://example.com/arroyo-home-vet', 'Home visit from $95', 7, null, true)
) as v(user_id, business_name, contact_name, headline, about, services, cities, phone, email, website, rate_note, years, credentials, insured);

insert into public.events (title, event_date, event_time, location, description, host)
select v.title, current_date + v.days, v.time, v.location, v.description, 'Desert Springs Dog Dad'
from (values
  ('Sunday Morning Dog Walk', 3, '08:00 AM', 'Cactus Flats Dog Park, Cactus Flats', 'A relaxed loop around the park followed by coffee. All sizes and ages welcome.'),
  ('Yappy Hour on the Patio', 9, '05:30 PM', 'Cholla Brewing Co., Oasis Park', 'Monthly meetup. Water bowls and treats provided. Dogs must be friendly and leashed.'),
  ('Puppy Social Hour', 15, '10:00 AM', 'Mesa Verde Commons, Mesa Verde', 'A small playdate for puppies under six months. Vaccinations up to date, please.'),
  ('Trail Clean Up Day', 21, '09:00 AM', 'Arroyo Trail trailhead', 'Bring gloves and a water bottle. Leashed dogs welcome.'),
  ('Adoption Day Volunteer Morning', 27, '09:30 AM', 'Desert Springs Humane Society', 'Help greet visitors, walk dogs and set up tables.'),
  ('Senior Dog Stroll', 33, '04:00 PM', 'Arroyo Trail, shaded section', 'A slow-paced walk for older dogs and their people.')
) as v(title, days, time, location, description);

-- RESULT. Expected: members 120, threads 48, replies 247, listings 30, events 6, not_example_accounts 0.
select
  (select count(*) from public.profiles where confirmed)                 as members,
  (select count(*) from public.forum_posts)                              as threads,
  (select count(*) from public.forum_replies)                            as replies,
  (select count(*) from public.pro_listings where status = 'published')  as listings,
  (select count(*) from public.events)                                   as events,
  (select count(*) from auth.users
     where lower(coalesce(email, '')) not like '%@example.com')          as not_example_accounts;
